
//AUTOGENERATED_TEXT_E6585F83424849_START
#ifndef INCLUDE_GAURD_E6585F83424849_INCLUDE_GLOAM_CORE_UTIL_DCG_STL_SMARTPTRS_HPP
#define INCLUDE_GAURD_E6585F83424849_INCLUDE_GLOAM_CORE_UTIL_DCG_STL_SMARTPTRS_HPP
//AUTOGENERATED_TEXT_E6585F83424849_END

#include "dcg/stl/range_t.hpp"
#include "dcg/stl/c_vector.hpp"

#include <memory>
#include <string>

//AUTOGENERATED_TEXT_E6585F83424849_START
namespace gloam{
//AUTOGENERATED_TEXT_E6585F83424849_END

//common types and functions from the standard template library.
//and clean_stl_vector::vector in place of std::vector.

using std::string;

template<typename T>
using u_ptr = std::unique_ptr<T>;
//
template<typename T>
using s_ptr = std::shared_ptr<T>;
template<typename T>
using w_ptr = std::weak_ptr<T>;

using std::make_unique;
template<typename T, typename... Args>
s_ptr<T> make_u(Args... args){ return(std::make_unique<T>(args...)); }

using std::make_shared;
template<typename T, typename ... Args>
s_ptr<T> make_s(Args... args){ return(std::make_shared<T>(args...)); }

//typedef std::make_unique make_u;
//typedef std::make_shared make_s;


//AUTOGENERATED_TEXT_E6585F83424849_START
}
#endif
/*Copyright (c) 2016, Dylan Carleton Gundlach

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
//AUTOGENERATED_TEXT_E6585F83424849_END
