
//AUTOGENERATED_TEXT_75206455E9C4A819_START
#ifndef INCLUDE_GAURD_75206455E9C4A819_INCLUDE_GLFW_HPP
#define INCLUDE_GAURD_75206455E9C4A819_INCLUDE_GLFW_HPP
//AUTOGENERATED_TEXT_75206455E9C4A819_END

//#include "util.hpp"

#include <GLFW/glfw3.h>

//AUTOGENERATED_TEXT_75206455E9C4A819_START
namespace glob{
//AUTOGENERATED_TEXT_75206455E9C4A819_END

class Glfw{
	//vector<GLFWmonitor*> monitors;

public:
	static void init(){
		if (!glfwInit())
			exit(-1);
		glfwSetErrorCallback(
			[](int i, const char* s){
				cout 
					<< "a fatal glfw error occured: " 
					<< "code: " << i << endl
					<< "description: " << s << endl
				;
				cout.flush();
				std::exit(-1);
			}
		);
		//
		/*int count;
		GLFWmonitor** ms = glfwGetMonitors(&count);
		for(int i = 0; i < count; i++){
			monitors.push_back(ms[i]);
		}*/
	}

	//const vector<GLFWmonitor*>& getMonitors(){ return(monitors); }
};


//AUTOGENERATED_TEXT_75206455E9C4A819_START
}
#endif
/*No Message
*/
//AUTOGENERATED_TEXT_75206455E9C4A819_END
