
//AUTOGENERATED_TEXT_E6585F83424849_START
#ifndef INCLUDE_GAURD_E6585F83424849_INCLUDE_GLOAM_CORE_PIXELSTORE_HPP
#define INCLUDE_GAURD_E6585F83424849_INCLUDE_GLOAM_CORE_PIXELSTORE_HPP
//AUTOGENERATED_TEXT_E6585F83424849_END

//AUTOGENERATED_TEXT_E6585F83424849_START
namespace gloam{
//AUTOGENERATED_TEXT_E6585F83424849_END


/*class PixelStoreSettings{
private:
	template<class T>
	struct Setting{
		bool b_modified = false;
		T restore;

		Setting(){}
	};

private:
	bool b_pack;
public:
	Setting<bool> swap_bytes;
	Setting<bool> lsb_first;
	Setting<int> row_length;
	Setting<int> image_height;
	Setting<int> skip_rows;
	Setting<int> skip_pixels;
	Setting<int> skip_images;
	Setting<int> alignment;

public:
	//default settings
	PixelStoreSettings() :	
		swap_bytes(			false),
		lsb_first(			false),
		row_length(			0),
		image_height(		0),
		skip_rows(			0),
		skip_pixels(		0),
		skip_images(		0),
		alignment(			4)
	{}

	PixelStoreSettings(
		bool swap_bytes,
		bool lsb_first,
		int row_length,
		int image_height,
		int skip_rows,
		int skip_pixels,
		int skip_images,
		int alignment
	) :	
		swap_bytes(swap_bytes),
		lsb_first(lsb_first),
		row_length(row_length),
		image_height(image_height),
		skip_rows(skip_rows),
		skip_pixels(skip_pixels),
		skip_images(skip_images),
		alignment(alignment)
	{}

	void push(){
		
	}


ROW_LENGTH,
IMAGE_HEIGHT,
SKIP_ROWS,
SKIP_PIXELS,
SKIP_IMAGES,
ALIGNMENT
SWAP_BYTES,
LSB_FIRST,


bool swap_bytes;
bool lsb_first;
int row_length;
int image_height;
int skip_rows;
int skip_pixels;
int skip_images;
int alignment;

private:
	void store(){
		PixelStoreSettings current();
		glGetIntegerv(current
	}









};*/

//AUTOGENERATED_TEXT_E6585F83424849_START
}
#endif
/*Copyright (c) 2016, Dylan Carleton Gundlach

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
//AUTOGENERATED_TEXT_E6585F83424849_END
